#!/bin/env sh

# .config
CONFIGS=(electron25-flags.conf fish foot nvim mako sway)
mkdir -p .config 
for CONFIG in "${CONFIGS[@]}"; do
	cp -r ~/.config/$CONFIG .config
done

pacman -Qenq > packages.txt
pacman -Qemq > aurpackages.txt
